name: Daily update of README

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */1 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
        with:
          ref: ${{ github.ref_name }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install requests
        run: pip install requests

      - name: Run weather
        run: python weather_in_warsaw.py
        env:
          WEATHER_KEY: ${{  secrets.WEATHER_KEY  }}

      - name: Push new README.md
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{  secrets.GITHUB_TOKEN  }}
          BRANCH_NAME: main