name: Daily update of README

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */1 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run weather
        run: python weather_in_warsaw.py
        env:
          WEATHER_KEY: ${{secrets.WEATHER_KEY}}

      - name: update file and push to remote
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add -A
          git commit -m "Update README.md"
          git push